name: Deploy Medusa Backend to ECS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vikky17/medusa:latest

    steps:
    - name: ğŸ§¾ Checkout Repository
      uses: actions/checkout@v3

    - name: ğŸ” Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: ğŸ³ Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: ğŸ› ï¸ Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: ğŸ“¦ Terraform Init
      run: terraform init
      working-directory: ./pearlthoughts-project/terraform

    - name: ğŸ” Terraform Plan
      run: terraform plan -var="medusa_image=$IMAGE_NAME"
      working-directory: ./pearlthoughts-project/terraform

    - name: ğŸš€ Terraform Apply
      run: terraform apply -auto-approve -var="medusa_image=$IMAGE_NAME"
      working-directory: ./pearlthoughts-project/terraform
